"""Map frames: one UUID-named directory per state of the world that was drawn.

The maps are namespaced by build like every other component's output
(`maps/data/<build>/`, from `lib/builds.py:component_data`), and inside that a
frame is a UUID with a row in `INDEX.json` saying what it is. A name built out
of the step or the label that produced it would separate frames only along the
dimensions it encoded -- the trap CLAUDE.md rule 6 records for ExoPlaSim runs
and LPJ-GUESS runs, which collided that way -- and a map is drawn from four
things at once: the terrain, the classification, the climatology and the lake
solution. So the name says nothing and the manifest says everything.

**A frame is identified by its INPUTS, not by when it was rendered.** The
fingerprint is a hash over the identity of those four inputs, and the same
fingerprint is the same picture: a snapshot taken at a step that moved none of
them reuses the frame that exists and records the step against it. That is what
makes "render after every step" cheap, and it is also what makes the series
honest -- a new frame appears exactly where the world changed.

`INDEX.json` IS tracked; the frames are not. Same rule as `exoplasim/runs/`:
the payload is regenerable while the inputs survive, and the index is the only
record of what a UUID was once they do not.
"""

from __future__ import annotations

import hashlib
import json
import subprocess
import sys
import uuid
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
from lib import builds  # noqa: E402

NOTE = ("What each map frame is. Frame ids are UUIDs and carry no meaning; a "
        "frame is identified by the inputs it was drawn from, and two states of "
        "the world that differ in none of them are one frame. Generated by "
        "maps/render_projections.py and maps/snapshot.py; do not edit.")


def data_dir(config: dict | None = None) -> Path:
    """`maps/data/<build>/`. Never the flat directory; see `builds.py`."""
    return builds.component_data("maps", config)


def index_path(config: dict | None = None) -> Path:
    return data_dir(config) / "INDEX.json"


def sha256(path: Path | None) -> str | None:
    """Content hash of a file, or None where the file is absent.

    None is a value here rather than an error: the lake solution is optional
    (`build_basemap.py:load_surface_water` draws without it), so "no surface
    water" is a state of the world the fingerprint has to be able to express.
    """
    if path is None or not Path(path).is_file():
        return None
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        while chunk := fh.read(1 << 20):
            h.update(chunk)
    return h.hexdigest()


def inputs(*, source_build: str, terrain_hash: str, climatology: Path,
           classification: Path, surface_water: Path | None) -> dict:
    """The identity of everything a map is drawn from.

    Four inputs, and the hash of each rather than its path: a climatology
    rebuilt from a longer window keeps its filename and is a different world.
    The paths are carried alongside so a reader can say WHICH product, but they
    are not what the fingerprint is taken over.
    """
    def rel(p: Path | None) -> str | None:
        """Repo-relative where it can be, absolute where it cannot.

        A climatology named from outside the tree is a legitimate argument and
        must land in the record as what it was, rather than raising here and
        losing the frame.
        """
        if p is None:
            return None
        p = Path(p).resolve()
        return str(p.relative_to(ROOT)) if p.is_relative_to(ROOT) else str(p)

    return {
        "source_build": source_build,
        "final_elevation_hash": terrain_hash,
        "climatology": rel(climatology),
        "climatology_sha256": sha256(climatology),
        "classification": rel(classification),
        "classification_sha256": sha256(classification),
        "surface_water": rel(surface_water),
        "surface_water_sha256": sha256(surface_water),
    }


def fingerprint(block: dict) -> str:
    """Hash over the input identities, taken on the hashes and not the paths."""
    keyed = {k: v for k, v in sorted(block.items()) if k.endswith("_hash")
             or k.endswith("_sha256") or k == "source_build"}
    return hashlib.sha256(
        json.dumps(keyed, sort_keys=True).encode("utf-8")).hexdigest()


def load(config: dict | None = None) -> dict:
    path = index_path(config)
    if path.is_file():
        return json.loads(path.read_text(encoding="utf-8"))
    return {"note": NOTE, "build": None, "generated": None, "frames": []}


def save(index: dict, config: dict | None = None) -> Path:
    path = index_path(config)
    path.parent.mkdir(parents=True, exist_ok=True)
    index["note"] = NOTE
    index["generated"] = datetime.now(timezone.utc).isoformat()
    path.write_text(json.dumps(index, indent=2) + "\n", encoding="utf-8")
    return path


def new_id() -> str:
    return f"map_{uuid.uuid4().hex[:12]}"


def find(index: dict, key: str) -> dict | None:
    """The frame drawn from these inputs, if one exists."""
    for entry in index.get("frames", []):
        if entry.get("fingerprint") == key:
            return entry
    return None


def open_frame(index: dict, block: dict, config: dict | None = None) -> dict:
    """The entry for this state of the world, created if it is a new one."""
    key = fingerprint(block)
    entry = find(index, key)
    if entry is None:
        entry = {
            "frame_id": new_id(),
            "fingerprint": key,
            "inputs": block,
            "steps": [],
            "outputs": {},
            "first_rendered": datetime.now(timezone.utc).isoformat(),
        }
        index.setdefault("frames", []).append(entry)
    index["build"] = block.get("source_build")
    entry["inputs"] = block
    return entry


def frame_dir(entry: dict, config: dict | None = None) -> Path:
    return data_dir(config) / entry["frame_id"]


def note_step(entry: dict, step: str | None) -> None:
    """Record that the world stood here when `step` had run.

    A frame accumulates steps rather than being replaced by one: several steps
    in a pass move nothing the map reads, and the honest record of that is one
    picture with several steps against it.
    """
    if step and step not in entry.setdefault("steps", []):
        entry["steps"].append(step)
    entry["last_recorded"] = datetime.now(timezone.utc).isoformat()


def needs_render(entry: dict, names: list[str], width: int,
                 supersample: int) -> list[str]:
    """Which of `names` this frame does not already hold at this size."""
    have = entry.get("outputs", {})
    out = []
    for name in names:
        rec = have.get(f"vesper_{name}.png")
        path = frame_dir(entry) / f"vesper_{name}.png"
        if (rec is None or not path.is_file()
                or rec.get("width") != width
                or rec.get("supersample") != supersample):
            out.append(name)
    return out


def map_steps() -> list[str]:
    """The pipeline steps a frame can stand after, from the graph itself.

    Derived by `scripts/pipeline.py:map_affecting` and never listed here:
    `config/pipeline.yaml` is the graph, and a second list of which steps touch
    the map would be a copy of it that goes stale the first time an edge moves.
    """
    if str(ROOT / "scripts") not in sys.path:
        sys.path.insert(0, str(ROOT / "scripts"))
    import pipeline
    graph = pipeline.load()
    return sorted(pipeline.map_affecting(pipeline.steps_by_id(graph)))


def check_step(step: str) -> None:
    """Refuse a step id the graph does not have, or that cannot move the map.

    A free-text label would let a typo file a frame under a step that does not
    exist, and the manifest is the only record of where in a pass a picture was
    taken. The second half of the check is the useful one: a step the map is not
    reachable from cannot have changed it, so recording a frame against it would
    assert something the graph says is false.
    """
    known = map_steps()
    if step not in known:
        raise SystemExit(
            f"`{step}` is not a step the map can change. The graph says these "
            f"are:\n    {', '.join(known)}\n"
            "(`python scripts/pipeline.py --plan <target>` prints them in order, "
            "each with its snapshot line.)")


def git_commit() -> str:
    return subprocess.run(["git", "-C", str(ROOT), "rev-parse", "HEAD"],
                          capture_output=True, text=True).stdout.strip()
