"""Map frames: one UUID-named directory per state of the world that was drawn.

The maps are namespaced by build like every other component's output
(`maps/data/<build>/`, from `lib/builds.py:component_data`), and inside that a
frame is a UUID with a row in `INDEX.json` saying what it is. A name built out
of the step or the label that produced it would separate frames only along the
dimensions it encoded -- the trap CLAUDE.md rule 6 records for ExoPlaSim runs
and LPJ-GUESS runs, which collided that way -- and a map is drawn from four
things at once: the terrain, the classification, the climatology and the lake
solution. So the name says nothing and the manifest says everything.

**A frame is identified by its INPUTS, not by when it was rendered.** The
fingerprint is a hash over the identity of those four inputs, and the same
fingerprint is the same picture: a snapshot taken at a step that moved none of
them reuses the frame that exists and records the step against it. That is what
makes "render after every step" cheap, and it is also what makes the series
honest -- a new frame appears exactly where the world changed.

`INDEX.json` IS tracked; the frames are not. Same rule as `exoplasim/runs/`:
the payload is regenerable while the inputs survive, and the index is the only
record of what a UUID was once they do not.

**The row is written before the picture is, and every write of it is locked.**
The index is a read-modify-write over one file, and a render is minutes long,
so an unlocked `load()` at the start and `save()` at the end drops whatever
another process recorded in between: its row goes and its directory stays, a
UUID of pixels nothing can name. Two processes reaching a new fingerprint at
once would also allocate two ids for one picture. `register()` closes both by
taking the id under the lock BEFORE anything is drawn -- the same rule that
made `exoplasim/runs/INDEX.json` a ledger -- and `record()` merges this frame's
row back in under the lock rather than writing the whole index from memory.
"""

from __future__ import annotations

import fcntl
import hashlib
import json
import shutil
import subprocess
import sys
import uuid
from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
from lib import builds  # noqa: E402

NOTE = ("What each map frame is. Frame ids are UUIDs and carry no meaning; a "
        "frame is identified by the inputs it was drawn from, and two states of "
        "the world that differ in none of them are one frame. Generated by "
        "maps/render_projections.py and maps/snapshot.py; do not edit.")


def data_dir(config: dict | None = None) -> Path:
    """`maps/data/<build>/`. Never the flat directory; see `builds.py`."""
    return builds.component_data("maps", config)


def index_path(config: dict | None = None) -> Path:
    return data_dir(config) / "INDEX.json"


def sha256(path: Path | None) -> str | None:
    """Content hash of a file, or None where the file is absent.

    None is a value here rather than an error: the lake solution is optional
    (`build_basemap.py:load_surface_water` draws without it), so "no surface
    water" is a state of the world the fingerprint has to be able to express.
    """
    if path is None or not Path(path).is_file():
        return None
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        while chunk := fh.read(1 << 20):
            h.update(chunk)
    return h.hexdigest()


def inputs(*, source_build: str, terrain_hash: str, climatology: Path,
           classification: Path, surface_water: Path | None) -> dict:
    """The identity of everything a map is drawn from.

    Four inputs, and the hash of each rather than its path: a climatology
    rebuilt from a longer window keeps its filename and is a different world.
    The paths are carried alongside so a reader can say WHICH product, but they
    are not what the fingerprint is taken over.
    """
    def rel(p: Path | None) -> str | None:
        """Repo-relative where it can be, absolute where it cannot.

        A climatology named from outside the tree is a legitimate argument and
        must land in the record as what it was, rather than raising here and
        losing the frame.
        """
        if p is None:
            return None
        p = Path(p).resolve()
        return str(p.relative_to(ROOT)) if p.is_relative_to(ROOT) else str(p)

    return {
        "source_build": source_build,
        "final_elevation_hash": terrain_hash,
        "climatology": rel(climatology),
        "climatology_sha256": sha256(climatology),
        "classification": rel(classification),
        "classification_sha256": sha256(classification),
        "surface_water": rel(surface_water),
        "surface_water_sha256": sha256(surface_water),
    }


def fingerprint(block: dict) -> str:
    """Hash over the input identities, taken on the hashes and not the paths."""
    keyed = {k: v for k, v in sorted(block.items()) if k.endswith("_hash")
             or k.endswith("_sha256") or k == "source_build"}
    return hashlib.sha256(
        json.dumps(keyed, sort_keys=True).encode("utf-8")).hexdigest()


def load(config: dict | None = None) -> dict:
    path = index_path(config)
    if path.is_file():
        return json.loads(path.read_text(encoding="utf-8"))
    return {"note": NOTE, "build": None, "generated": None, "frames": []}


def save(index: dict, config: dict | None = None) -> Path:
    path = index_path(config)
    path.parent.mkdir(parents=True, exist_ok=True)
    index["note"] = NOTE
    index["generated"] = datetime.now(timezone.utc).isoformat()
    path.write_text(json.dumps(index, indent=2) + "\n", encoding="utf-8")
    return path


def new_id() -> str:
    return f"map_{uuid.uuid4().hex[:12]}"


def find(index: dict, key: str) -> dict | None:
    """The frame drawn from these inputs, if one exists."""
    for entry in index.get("frames", []):
        if entry.get("fingerprint") == key:
            return entry
    return None


def open_frame(index: dict, block: dict, config: dict | None = None) -> dict:
    """The entry for this state of the world, created if it is a new one."""
    key = fingerprint(block)
    entry = find(index, key)
    if entry is None:
        entry = {
            "frame_id": new_id(),
            "fingerprint": key,
            "inputs": block,
            "steps": [],
            "outputs": {},
            "first_rendered": datetime.now(timezone.utc).isoformat(),
        }
        index.setdefault("frames", []).append(entry)
    index["build"] = block.get("source_build")
    entry["inputs"] = block
    return entry


@contextmanager
def locked(config: dict | None = None):
    """Exclusive access to this build's frame index, for one read-modify-write.

    On a lock file beside the index rather than on the index itself, so the
    atomic replace `save()` does cannot drop the lock a waiter is holding.
    `maps/.gitignore` already excludes everything in a build's data directory
    but the index, so the lock file is untracked without a rule of its own.
    """
    path = index_path(config)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path.with_name(path.name + ".lock"), "w", encoding="utf-8") as fh:
        fcntl.flock(fh, fcntl.LOCK_EX)
        yield


def register(block: dict, config: dict | None = None) -> dict:
    """The row for this state of the world, IN THE INDEX before anything is drawn.

    A frame id is a UUID and the index is the only record of what one was, so
    the id and its row are taken together, under the lock, at the moment the
    frame comes into existence. Rendering first and recording afterwards leaves
    a window in which the directory exists and nothing names it, and makes two
    processes at one fingerprint allocate two ids for one picture.
    """
    with locked(config):
        index = load(config)
        entry = open_frame(index, block, config)
        save(index, config)
    return entry


def record(entry: dict, config: dict | None = None) -> Path:
    """Merge this frame's row back into the index on disk, under the lock.

    Re-read rather than written from the caller's copy of the whole index: the
    copy is as old as the render, and writing it back would delete every row
    another process added meanwhile. Outputs and steps are unioned for the same
    reason within one frame -- two renders can extend one frame with different
    projections, and neither is the whole of it.
    """
    with locked(config):
        index = load(config)
        rows = index.setdefault("frames", [])
        for i, row in enumerate(rows):
            if row.get("frame_id") == entry["frame_id"]:
                merged = {**row, **entry}
                merged["outputs"] = {**row.get("outputs", {}),
                                     **entry.get("outputs", {})}
                merged["steps"] = list(dict.fromkeys(
                    list(row.get("steps", [])) + list(entry.get("steps", []))))
                rows[i] = merged
                break
        else:
            rows.append(entry)
        index["build"] = entry.get("inputs", {}).get("source_build")
        return save(index, config)


def frame_dir(entry: dict, config: dict | None = None) -> Path:
    return data_dir(config) / entry["frame_id"]


def note_step(entry: dict, step: str | None) -> None:
    """Record that the world stood here when `step` had run.

    A frame accumulates steps rather than being replaced by one: several steps
    in a pass move nothing the map reads, and the honest record of that is one
    picture with several steps against it.
    """
    if step and step not in entry.setdefault("steps", []):
        entry["steps"].append(step)
    entry["last_recorded"] = datetime.now(timezone.utc).isoformat()


def needs_render(entry: dict, names: list[str], width: int,
                 supersample: int) -> list[str]:
    """Which of `names` this frame does not already hold at this size."""
    have = entry.get("outputs", {})
    out = []
    for name in names:
        rec = have.get(f"vesper_{name}.png")
        path = frame_dir(entry) / f"vesper_{name}.png"
        if (rec is None or not path.is_file()
                or rec.get("width") != width
                or rec.get("supersample") != supersample):
            out.append(name)
    return out


def map_steps() -> list[str]:
    """The pipeline steps a frame can stand after, from the graph itself.

    Derived by `scripts/pipeline.py:map_affecting` and never listed here:
    `config/pipeline.yaml` is the graph, and a second list of which steps touch
    the map would be a copy of it that goes stale the first time an edge moves.
    """
    if str(ROOT / "scripts") not in sys.path:
        sys.path.insert(0, str(ROOT / "scripts"))
    import pipeline
    graph = pipeline.load()
    return sorted(pipeline.map_affecting(pipeline.steps_by_id(graph)))


def check_step(step: str) -> None:
    """Refuse a step id the graph does not have, or that cannot move the map.

    A free-text label would let a typo file a frame under a step that does not
    exist, and the manifest is the only record of where in a pass a picture was
    taken. The second half of the check is the useful one: a step the map is not
    reachable from cannot have changed it, so recording a frame against it would
    assert something the graph says is false.
    """
    known = map_steps()
    if step not in known:
        raise SystemExit(
            f"`{step}` is not a step the map can change. The graph says these "
            f"are:\n    {', '.join(known)}\n"
            "(`python scripts/pipeline.py --plan <target>` prints them in order, "
            "each with its snapshot line.)")


def git_commit() -> str:
    return subprocess.run(["git", "-C", str(ROOT), "rev-parse", "HEAD"],
                          capture_output=True, text=True).stdout.strip()


def _self_test() -> list[str]:
    """The three identity questions, on a throwaway index. Called by the gate.

    Class 17: each has a right answer rather than a value to differ from. A
    render is minutes long and interleaves with another process's, so the
    fixture interleaves them -- both register, then both record -- which is
    exactly the order an unlocked read-modify-write loses a row in.
    """
    import tempfile

    bad = []
    here = index_path
    tmp = Path(tempfile.mkdtemp(prefix="frames_self_test_"))
    globals()["index_path"] = lambda config=None: tmp / "INDEX.json"
    try:
        one = {"source_build": "b", "final_elevation_hash": "aa",
               "climatology_sha256": "1"}
        two = dict(one, climatology_sha256="2")
        a, b = register(one), register(two)
        a["outputs"] = {"vesper_x.png": {"width": 1}}
        note_step(a, "step-a")
        record(a)
        b["outputs"] = {"vesper_y.png": {"width": 2}}
        record(b)

        rows = load()["frames"]
        if len(rows) != 2:
            bad.append(f"two frames registered and the index holds {len(rows)}: "
                       "one render's row was overwritten by another's, and its "
                       "directory is a UUID nothing can name")
        if register(one)["frame_id"] != a["frame_id"]:
            bad.append("one fingerprint was given two frame ids, so one "
                       "picture is two rows and one of the directories is a "
                       "duplicate nothing distinguishes")
        stale = dict(a, outputs={"vesper_z.png": {"width": 3}}, steps=["step-c"])
        record(stale)
        got = [r for r in load()["frames"] if r["frame_id"] == a["frame_id"]][0]
        if sorted(got["outputs"]) != ["vesper_x.png", "vesper_z.png"]:
            bad.append(f"a second render of one frame replaced its outputs "
                       f"instead of extending them: {sorted(got['outputs'])}")
        if got.get("steps") != ["step-a", "step-c"]:
            bad.append(f"the steps a frame stands after do not accumulate: "
                       f"{got.get('steps')}")
    finally:
        globals()["index_path"] = here
        shutil.rmtree(tmp, ignore_errors=True)
    return bad
