#!/usr/bin/env python3
"""Build the LPJ-GUESS binary and record the source it was built from.

    python biosphere/scripts/build_lpj_guess.py            # configure, build, stamp
    python biosphere/scripts/build_lpj_guess.py --verify   # check, build nothing

Worldbuilding frame: this compiles the C++ ecosystem model the biosphere
component runs. Nothing here concerns the simulated planet; it is a property of
the source text and of the executable on disk.

WHY THIS EXISTS. LPJ-GUESS compiles one executable from a hundred and thirty
translation units and reads none of them at run time, so a binary built before
an edit runs the code it was built from and says nothing. Rule 4 states that
hazard for ExoPlaSim and `rebuild_binaries.py --verify` closes it there; the
biosphere had no equivalent. It fired on 2026-08-30: `vendor/lpj-guess/build/guess`
was two days older than `framework/parameters.cpp` and did not know
`frac_labile_carbon_humus`, and the run refused only because that parameter
reaches the model through an instruction file, so the PARSER rejected an
undefined identifier. A change confined to C++ -- a constant, a rate law, one of
the `ntransform.cpp` divergences this project has made against mainline -- has
no parser between it and the run. It would have integrated to completion on a
binary that did not contain it, and every number out of it would have been
attributed to source the run never executed. world-w62x.

CONTENT SHAS, NOT MTIMES, and that is the whole design. A modification time
answers "which file is younger", which is neither necessary nor sufficient: a
`git checkout`, a rebase or `scripts/link_worktree.py` rewrites the mtime of a
file whose bytes did not move, so mtimes refuse builds that are correct, and a
binary copied in from elsewhere carries the mtime of the copy and passes against
any source at all. Hashing what is on disk subsumes both. Mtimes appear in this
module exactly once, in `describe()`, as a HUMAN AID beside a sha that has
already decided the verdict -- world-w62x's acceptance asks for the newer files
to be named, and a date is how a reader recognises the edit they made.

IT DOES NOT BUILD IN ORDER TO CHECK. `--verify` hashes files and reads a JSON
document; it spawns no compiler. Making the check a rebuild was considered and
refused twice over: it is a rule 8 tier violation for a check that has to be
cheap enough to run in front of every run, and a rebuild REPLACES the executable
whose sha a concurrent run's manifest has already recorded. A gate must not
mutate the artifact it is judging. `verify_model_compiles.py` refuses to build
for the first of those reasons; this refuses for both.

WHERE THE RECORD LIVES. Beside the binary, as `guess.provenance.json`, and not
in a tracked manifest. That is the convention `prepare_stock_ntransform_arm.py`
already established in this component -- `binary.with_suffix(".provenance.json")`
carrying a `binary_sha256` and a source fingerprint -- and `run_lpj_guess.py`
already reads exactly that path for the stock arm, so extending it to every
binary adds no second concept. It is untracked because the binary is: this build
is not known to be reproducible across paths, `build/` is deliberately NOT
linked into a worktree (`scripts/link_worktree.py`), and a tracked manifest
would make one agent's rebuild dirty another agent's tree. ExoPlaSim tracks its
manifest because its build IS bit-reproducible and path-independent
(`exoplasim/scripts/verify_build_path_independence.py` holds that); the argument
does not carry over here, so neither does the choice.

THE SOURCE SET IS READ OUT OF THE BUILD FILES, then closed over `#include`.
`framework/CMakeLists.txt` and its three siblings declare `headers` and `source`
lists which `cmake/add_guess_sources.cmake` accumulates into `guess_sources`,
and the top-level `add_executable` adds `command_line_version/main.cpp`. Those
lists are the declaration and a glob is not: `windows_version/`, `tests/` and
`benchmarks/` hold C++ that this configuration compiles nowhere, and hashing
them reports a stale binary every time somebody edits a file no compiled line
reaches. But the declared lists are not the whole input either --
`framework/vesper.h` is generated by `build_vesper_header.py`, is gitignored,
sizes arrays at compile time, appears in no CMakeLists, and reaches every
translation unit through `guessmath.h`. A set that misses it misses the file
most able to make a binary silently wrong. So the declared lists seed a walk
over local `#include "..."` resolved against the build file's own include path,
and what that walk reaches is what the executable is built from.

THE BUILD FILES AND THE TOOLCHAIN ARE PART OF WHAT A BINARY IS. `BUILD_INPUTS`
hashes the CMakeLists that decide the source set and the cmake modules they
include, because a change to either changes the executable while every source
sha stands still -- ExoPlaSim lost that same file-one-over for a while
(world-ynpx). `toolchain()` records the compiler and the configured cache
entries, so a sha that moved under unchanged sources is ATTRIBUTED rather than
reported as unknown provenance. Whether MPI and NetCDF were found is in there:
both are `add_definitions` in the top-level CMakeLists, so both change the code
that compiles.

RESTATED, THEN CROSS-CHECKED. `SUBDIRS`, `ENTRY` and `INCLUDE_DIRS` restate what
the top-level CMakeLists says, and `assert_build_file_shape()` fails when the
build file no longer agrees. A gate that derived them from the file it is
checking could not notice a fifth subdirectory going unhashed; a restatement
that is never compared is the silence rule 4 exists to break. This is
`rebuild_binaries.py:assert_threaded_flags_agree` applied to a different build
system, and `docs/src/practice/failure-modes.md` class 17 is why.
"""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
import hashlib
import importlib.util
import json
from pathlib import Path
import re
import subprocess
import sys

# `_paths` BY LOCATION, not by name. Every component has a module called
# `_paths`, and this one is imported INTO other components' processes:
# `scripts/check_consistency.py` appends `exoplasim/scripts` to `sys.path`
# first, so by the time this module loads, `sys.modules["_paths"]` is
# ExoPlaSim's and a plain `from _paths import GUESS_BINARY` raises ImportError
# -- which the gate reports as "not checked", the one verdict a staleness check
# must never quietly return. A gate that cannot import is a gate that is not
# running, and it looks exactly like a gate that passed.
_spec = importlib.util.spec_from_file_location(
    "biosphere_paths", Path(__file__).resolve().parent / "_paths.py")
_paths = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_paths)
GUESS_BINARY = _paths.GUESS_BINARY
GUESS_BUILD = _paths.GUESS_BUILD
GUESS_SOURCE = _paths.GUESS_SOURCE
PROJECT_ROOT = _paths.PROJECT_ROOT

CONTRACT = "vesper-lpj-guess-binary/1"
PROVENANCE = GUESS_BINARY.with_suffix(".provenance.json")

# The unconditional `add_subdirectory` calls in vendor/lpj-guess/CMakeLists.txt.
# `windows_version` is behind `if (WIN32)` and `tests` behind `if (UNIT_TESTS)`,
# and neither is compiled here. Restated so a fifth one fails the shape check
# rather than going unhashed.
SUBDIRS = ("framework", "modules", "cru", "libraries")

# The one translation unit the top-level `add_executable` adds directly.
ENTRY = "command_line_version/main.cpp"

# The `include_directories(...)` line, in its order. A quoted `#include` is
# resolved against the including file's own directory first, then these.
INCLUDE_DIRS = ("framework", "libraries/gutil", "libraries/plib",
                "libraries/guessnc", "modules", "cru/guessio")

# Files that decide the bytes and that the source walk cannot reach: the build
# files that name the source set, and the cmake modules they include. Relative
# to GUESS_SOURCE. `add_test_sources.cmake` is not here -- it is included only
# under UNIT_TESTS, which this configuration has OFF.
BUILD_INPUTS = ("CMakeLists.txt",
                "framework/CMakeLists.txt",
                "modules/CMakeLists.txt",
                "cru/CMakeLists.txt",
                "libraries/CMakeLists.txt",
                "cmake/add_guess_sources.cmake",
                "cmake/FindNetCDF.cmake")

# Configured values that change the compiled code or the flags it is compiled
# with. NETCDF_* and MPI_* are absent from the cache when the package is not
# found, and their absence is recorded as None: `HAVE_NETCDF` and `HAVE_MPI`
# are `add_definitions` in the top-level CMakeLists, so found-or-not is part of
# what the binary IS.
CACHE_KEYS = ("CMAKE_BUILD_TYPE", "CMAKE_CXX_COMPILER", "CMAKE_CXX_FLAGS",
              "CMAKE_CXX_FLAGS_RELEASE", "UNIT_TESTS", "SYSTEM",
              "MPI_CXX_COMPILER", "NETCDF_INCLUDE_DIR", "NETCDF_C_LIBRARY")

_SET_LIST = re.compile(r"^\s*set\s*\(\s*(headers|source)\b(.*?)\)", re.S | re.M)
_QUOTED_INCLUDE = re.compile(r'^\s*#\s*include\s*"([^"]+)"', re.M)


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def build_file_shape() -> list[str]:
    """Ways the top-level build file no longer says what this module restates.

    Restating the build file is what lets this module notice a source directory
    the build file grew and this one does not hash. A restatement nothing
    compares is the defect it exists to catch, so `verify()` runs this FIRST:
    a source set computed from a stale restatement passes a binary containing
    code from a directory nothing hashed, which is the silence the whole row is
    about. Returned rather than raised, so a gate that wraps this reports a
    failure instead of being killed by a `SystemExit` no `except Exception`
    catches.
    """
    out = []
    text = (GUESS_SOURCE / "CMakeLists.txt").read_text(encoding="utf-8")
    # Unconditional only: the two guarded calls sit inside if(WIN32) and
    # if(UNIT_TESTS) and are indented, which is how the build file marks them.
    found = tuple(m[1].strip() for m in
                  re.finditer(r"^add_subdirectory\(([^)]+)\)", text, re.M))
    if found != SUBDIRS:
        out.append(
            f"vendor/lpj-guess/CMakeLists.txt compiles {found} unconditionally "
            f"and this module hashes {SUBDIRS}. Update SUBDIRS: a directory "
            f"this does not hash is a directory a stale binary hides in.")
    if ENTRY not in text:
        out.append(
            f"vendor/lpj-guess/CMakeLists.txt no longer names {ENTRY} in its "
            f"add_executable line, so the entry point this module hashes is "
            f"not the one it builds.")
    line = re.search(r"^include_directories\(([^)]*)\)", text, re.M)
    if line is None:
        out.append(
            "vendor/lpj-guess/CMakeLists.txt has no include_directories line, "
            "so the path a quoted #include resolves against is unknown here.")
    else:
        got = tuple(d.split("}/")[-1] for d in line[1].split())
        if got != INCLUDE_DIRS:
            out.append(
                f"the build file's include path is {got} and this module "
                f"resolves quoted includes against {INCLUDE_DIRS}. A header "
                f"found on one path and not on the other goes unhashed.")
    return out


def declared() -> list[Path]:
    """The translation units and headers the build files list, as absolute paths.

    Read out of the four subdirectory CMakeLists rather than globbed, for the
    reason `rebuild_binaries.py:model_sources` gives: a glob hashes files no
    configuration compiles, and editing one then reports the binary stale when
    no compiled line moved.
    """
    out: list[Path] = []
    for sub in SUBDIRS:
        cmake = GUESS_SOURCE / sub / "CMakeLists.txt"
        listed = [name for m in _SET_LIST.finditer(cmake.read_text(encoding="utf-8"))
                  for name in m[2].split()]
        if not listed:
            raise SystemExit(
                f"{cmake} declares no headers or source, so either the build "
                f"file changed shape or this parser no longer reads it.")
        out += [GUESS_SOURCE / sub / name for name in listed]
    out.append(GUESS_SOURCE / ENTRY)
    missing = [p for p in out if not p.is_file()]
    if missing:
        raise SystemExit("the build files list sources that are not on disk: "
                         + ", ".join(str(p.relative_to(GUESS_SOURCE)) for p in missing))
    return out


def resolve(include: str, origin: Path) -> Path | None:
    """A quoted `#include` against the compiler's search path, or None if system."""
    for base in [origin.parent] + [GUESS_SOURCE / d for d in INCLUDE_DIRS]:
        candidate = base / include
        if candidate.is_file():
            return candidate
    return None


def source_set() -> dict[str, str]:
    """Every file the executable is compiled from, relative path to sha256.

    The declared lists seed a closure over quoted `#include`, because the
    declaration is not complete: `framework/vesper.h` is generated, gitignored,
    named in no CMakeLists, and reaches every unit through `guessmath.h`. It is
    also the file most able to make a binary silently wrong, since the orbital
    year it carries sizes arrays at compile time.

    Paths are relative to `vendor/lpj-guess` and the values are content shas,
    so the record reads the same in a worktree as in the main checkout.
    """
    pending, seen = declared(), {}
    while pending:
        path = pending.pop()
        rel = str(path.relative_to(GUESS_SOURCE))
        if rel in seen:
            continue
        seen[rel] = sha256(path)
        text = path.read_text(encoding="utf-8", errors="replace")
        for name in _QUOTED_INCLUDE.findall(text):
            found = resolve(name, path)
            # An unresolved quoted include is a system header the compiler finds
            # on its own path; this tree quotes both kinds. That is toolchain
            # rather than model source, and `toolchain()` covers the toolchain.
            if found is not None:
                pending.append(found)
    for rel in BUILD_INPUTS:
        path = GUESS_SOURCE / rel
        if not path.is_file():
            raise SystemExit(f"the build is missing {rel}")
        seen[rel] = sha256(path)
    return dict(sorted(seen.items()))


def source_digest(sources: dict[str, str]) -> str:
    """One sha over the whole source map, for a record that cannot carry 124.

    A run manifest is tracked and there is one per run, so the map itself does
    not belong in it; this digest plus `subtree_commit` identifies the source
    state the executable contains, and the map beside the binary says which file
    moved when the digest disagrees.
    """
    canonical = json.dumps(dict(sorted(sources.items())), sort_keys=True)
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def cache_values() -> dict[str, str | None]:
    """The configured entries that decide the compiled code, or None if unset."""
    cache = GUESS_BUILD / "CMakeCache.txt"
    if not cache.is_file():
        return {k: None for k in CACHE_KEYS}
    found: dict[str, str] = {}
    for line in cache.read_text(encoding="utf-8", errors="replace").splitlines():
        m = re.match(r"^([A-Za-z0-9_]+):[A-Z]+=(.*)$", line)
        if m and m[1] in CACHE_KEYS:
            found[m[1]] = m[2]
    return {k: found.get(k) for k in CACHE_KEYS}


def toolchain() -> dict:
    """The compiler and the configuration a build is about to use.

    `source_set()` answers "what source went in" and cannot answer "what turned
    it into this executable". Without this, a sha that moved under unchanged
    sources is noticed and not attributed, which is the distinction
    `rebuild_binaries.py:toolchain` draws.
    """
    versions = {}
    for exe in ("c++", "cmake", "mpicxx"):
        try:
            r = subprocess.run([exe, "--version"], capture_output=True, text=True)
            versions[exe] = r.stdout.splitlines()[0].strip() if r.stdout else None
        except (OSError, IndexError):
            versions[exe] = None
    return {"versions": versions, "cache": cache_values()}


def subtree_commit() -> str | None:
    """The commit `vendor/lpj-guess` last moved on, recorded but never trusted.

    A commit says what was COMMITTED; the shas above say what is on disk. An
    uncommitted edit under vendor/ is what the shas catch and this cannot.
    """
    try:
        r = subprocess.run(
            ["git", "log", "-1", "--format=%H", "--", "vendor/lpj-guess"],
            cwd=PROJECT_ROOT, capture_output=True, text=True)
        return r.stdout.strip() or None
    except OSError:
        return None


def describe_drift(prior: dict, current: dict) -> list[str]:
    """Toolchain differences, one line each."""
    out = []
    for group in ("versions", "cache"):
        keys = set(prior.get(group, {})) | set(current.get(group, {}))
        for key in sorted(keys):
            was, now = prior.get(group, {}).get(key), current.get(group, {}).get(key)
            if was != now:
                out.append(f"{group}.{key}: built with {was!r}, now {now!r}")
    return out


def describe(rel: str, recorded: str | None) -> str:
    """One changed source, with the mtime a reader recognises the edit by.

    The sha has already decided the verdict. The date is here because
    world-w62x's acceptance asks the refusal to NAME the files, and a bare
    relative path does not tell an operator which of their own edits this is.
    """
    path = GUESS_SOURCE / rel
    if not path.is_file():
        return f"  {rel}: was compiled in, and is no longer on disk"
    when = datetime.fromtimestamp(path.stat().st_mtime).strftime("%Y-%m-%d %H:%M")
    verb = "added since the build" if recorded is None else "changed since the build"
    return f"  {rel}: {verb}, modified {when}"


def verify(binary: Path = GUESS_BINARY) -> list[str]:
    """Why `binary` is not the executable this tree builds. Empty means it is.

    Hashes and a JSON read: no compiler is spawned and nothing is written, so
    this is cheap enough to sit in front of every run as well as in the gate.
    """
    shape = build_file_shape()
    if shape:
        # FIRST, and fatal on its own: a source set computed from a restatement
        # the build file has outgrown would report a stale binary current.
        return shape
    provenance = binary.with_suffix(".provenance.json")
    if not binary.is_file():
        return [f"{binary} does not exist. Build it with "
                f"`scripts/lock_and_run -m 'build lpj-guess' "
                f"python biosphere/scripts/build_lpj_guess.py`."]
    if not provenance.is_file():
        return [f"{binary} has no {provenance.name} beside it, so the source it "
                f"was built from is unknown. Rebuild it with "
                f"biosphere/scripts/build_lpj_guess.py, which records that."]
    try:
        record = json.loads(provenance.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        return [f"{provenance} is not readable JSON: {exc}"]
    if record.get("contract_version") != CONTRACT:
        return [f"{provenance} declares {record.get('contract_version')!r} and "
                f"this gate reads {CONTRACT!r}"]

    got = sha256(binary)
    if record.get("binary_sha256") != got:
        return [f"{binary.name} is {got[:16]} and {provenance.name} records "
                f"{str(record.get('binary_sha256'))[:16]}, so the record "
                f"describes a different executable than the one on disk"]

    problems = []
    recorded_sources = record.get("sources") or {}
    current = source_set()
    changed = [r for r in sorted(set(recorded_sources) | set(current))
               if recorded_sources.get(r) != current.get(r)]
    if changed:
        problems.append(
            f"{binary.name} was built from source that has since changed, so it "
            f"does not contain the model in this tree:\n"
            + "\n".join(describe(r, recorded_sources.get(r)) for r in changed))
    drift = describe_drift(record.get("toolchain") or {}, toolchain())
    if drift:
        problems.append(
            f"{binary.name} was built by a toolchain this tree no longer "
            f"configures:\n" + "\n".join("  " + d for d in drift))
    return problems


def stamp(configure: list[str], compile_command: list[str]) -> None:
    """Write the record beside the binary.

    The source set is read AFTER the build, which is the only honest ordering
    for a tree edited while the compiler ran: the shas then describe the tree at
    or after the last translation unit's view of it, and the next `--verify`
    refuses rather than passing a binary assembled from two states of the tree.
    """
    shape = build_file_shape()
    if shape:
        raise SystemExit("\n".join(shape) + "\n\nRefusing to stamp: the record "
                         "would describe a source set the build file has "
                         "outgrown, which reads as provenance and is not.")
    sources = source_set()
    record = {
        "contract_version": CONTRACT,
        "generated": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "binary_sha256": sha256(GUESS_BINARY),
        "subtree_commit": subtree_commit(),
        "source_digest": source_digest(sources),
        "toolchain": toolchain(),
        "configure_command": configure,
        "compile_command": compile_command,
        "sources": sources,
    }
    PROVENANCE.write_text(json.dumps(record, indent=2) + "\n", encoding="utf-8")
    print(f"{GUESS_BINARY} built from {len(record['sources'])} files")
    print(f"  recorded in {PROVENANCE}")


def build(jobs: int, build_type: str) -> None:
    """Configure, compile, then stamp. Stamping last, so a failed build stamps nothing.

    CPU-heavy: run it under `scripts/lock_and_run`. It replaces the executable a
    concurrent run's manifest has already hashed, so check `pgrep -x guess`
    before starting one.
    """
    shape = build_file_shape()
    if shape:
        # Before the two minutes, not after: a build this cannot honestly stamp
        # is a build worth refusing to start.
        raise SystemExit("\n".join(shape))
    header = GUESS_SOURCE / "framework" / "vesper.h"
    if not header.is_file():
        raise SystemExit(
            f"{header} does not exist, and the configured orbital year in it "
            f"sizes arrays at compile time. Run "
            f"`python biosphere/scripts/build_vesper_header.py` first.")
    configure = ["cmake", "-S", str(GUESS_SOURCE), "-B", str(GUESS_BUILD),
                 f"-DCMAKE_BUILD_TYPE={build_type}", "-DUNIT_TESTS=OFF"]
    compile_command = ["cmake", "--build", str(GUESS_BUILD), "--parallel", str(jobs)]
    subprocess.run(configure, check=True)
    subprocess.run(compile_command, check=True)
    if not GUESS_BINARY.is_file():
        raise SystemExit(f"the build reported success and {GUESS_BINARY} is not there")
    stamp(configure, compile_command)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--verify", action="store_true",
                    help="report whether the binary matches the tree; build nothing")
    ap.add_argument("--binary", type=Path, default=GUESS_BINARY,
                    help="executable to verify (default: the vendored one)")
    ap.add_argument("--jobs", type=int, default=16, help="parallel compile jobs")
    ap.add_argument("--build-type", default="Release", help="CMAKE_BUILD_TYPE")
    ap.add_argument("--stamp-only", action="store_true",
                    help="record the existing binary's source set without building")
    args = ap.parse_args()

    if args.verify:
        problems = verify(args.binary)
        for p in problems:
            print(p, file=sys.stderr)
        print("the LPJ-GUESS binary is stale" if problems
              else "the LPJ-GUESS binary matches the source it was built from")
        raise SystemExit(1 if problems else 0)
    if args.stamp_only:
        if not GUESS_BINARY.is_file():
            raise SystemExit(f"{GUESS_BINARY} does not exist, so there is "
                             f"nothing to stamp")
        stamp(["(not run: --stamp-only)"], ["(not run: --stamp-only)"])
        return
    build(args.jobs, args.build_type)


if __name__ == "__main__":
    main()
