"""Run LPJ-GUESS over Vesper, reproducibly and with its provenance recorded.

Every run before this one was hand-assembled in a scratch directory with a
hand-written instruction file, which is fine for a smoke test and not fine for
anything whose numbers get quoted. This is the equivalent of
`exoplasim/scripts/run_exoplasim.py`: it generates the instruction file, sets up
the rank directories, runs, merges the per-rank output and writes a manifest
pinning every input by hash.

    python biosphere/scripts/run_lpj_guess.py --nyear 50
    python biosphere/scripts/run_lpj_guess.py --ranks 16 --label carved-k25v

Bulk output lands in `runs/<run_id>/`, which is not tracked, in the same way
`exoplasim/runs/` is not. The manifest and a summary go to
`analysis/<run_id>/`, which is.

Three things this handles that catch people out:

**Absolute paths everywhere.** In parallel mode each rank chdirs into its own
`runN/` before reading anything, so a relative instruction path or a relative
`import` silently fails with "could not open ... for input".

**The rank split lives in the input module.** LPJ-GUESS normally splits work by
pre-splitting the gridlist file. `vesperinput` has no gridlist, so it strides the
cells itself; nothing here needs to divide anything.

**Fire and the weather generator.** `global.ins` selects BLAZE, which wants a
SimFIRE input file built from Earth observations, and GWGEN, which wants
sub-daily statistics we do not have. GLOBFIRM and INTERP are what the shipped
demo uses for the same reason.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import platform
import shutil
import subprocess
import time
from datetime import datetime, timezone
from pathlib import Path

import yaml

from _paths import (CONFIG, GENERATED, GUESS_BINARY, GUESS_SOURCE, PROJECT_ROOT,
                    RUNS)

import orbit

COMPONENT_ROOT = Path(__file__).resolve().parents[1]
ANALYSIS = COMPONENT_ROOT / "analysis"

# Output files worth keeping. LPJ-GUESS writes one per quantity, per rank.
#
# cflux.out carries the Fire column, which is the only fire diagnostic GLOBFIRM
# produces: firert.out and burned area are written under BLAZE only. Without it
# the burning is visible in cmass and dens as a mortality no output explains.
OUTPUTS = ("anpp.out", "lai.out", "fpc.out", "cmass.out", "aaet.out",
           "cpool.out", "dens.out", "agpp.out", "nsources.out", "cflux.out")


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def short(path: Path) -> str:
    return sha256(path)[:8]


def build_instruction(paths: dict, settings: dict) -> str:
    """The instruction file, with every path absolute. See the module docstring."""
    return f"""! GENERATED by biosphere/scripts/run_lpj_guess.py. Do not edit.
!
! Absolute paths throughout: in parallel mode each rank chdirs into its own
! runN/ directory before reading anything.

import "{paths['pfts']}"

title "{settings['title']}"
nyear {settings['nyear']}

file_driver "{paths['driver']}"
file_soilmap "{paths['soilmap']}"

! BLAZE needs a SimFIRE input file built from Earth observations and GWGEN needs
! sub-daily statistics this world does not have. The shipped demo makes the same
! two substitutions for the same reason.
firemodel "GLOBFIRM"
weathergenerator "INTERP"

npatch {settings['npatch']}
nfix_a {settings['nfix_a']}
nfix_b {settings['nfix_b']}

! Without this, soil carbon never reaches the hydrology and the soil-biosphere
! loop closes only inside pedology/. Stock LPJ-GUESS derives water-holding
! capacity from texture alone; iforganicsoilproperties makes it blend the
! mineral and organic water retention by the organic fraction, which is the
! path pedology's cpool.out feedback has to travel.
!
! It requires a SoilC column in the soil map, which build_soil.py writes, and it
! requires iftwolayersoil 0, which global.ins already sets.
iforganicsoilproperties 1

outputdirectory "./"
""" + "".join(
        f'file_{name.split(".")[0]} "{name}"\n' for name in OUTPUTS)


def merge_outputs(run_dir: Path, ranks: int) -> dict[str, int]:
    """Concatenate per-rank output, keeping one header.

    Rank directories each hold a complete set of files covering their own cells,
    so merging is a concatenation. The row count is returned per file so a rank
    that died quietly shows up as a short file rather than as a silently smaller
    planet.
    """
    counts = {}
    for name in OUTPUTS:
        pieces = [run_dir / f"run{rank}" / name for rank in range(1, ranks + 1)]
        pieces = [p for p in pieces if p.is_file()]
        if not pieces:
            continue
        target = run_dir / name
        with target.open("w") as out:
            for index, piece in enumerate(pieces):
                lines = piece.read_text().splitlines(keepends=True)
                if not lines:
                    continue
                out.writelines(lines if index == 0 else lines[1:])
        counts[name] = sum(1 for _ in target.read_text().splitlines()) - 1
    return counts


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--nyear", type=int, default=50,
                        help="simulation years after spin-up")
    parser.add_argument("--npatch", type=int, default=5,
                        help="replicate patches per gridcell")
    parser.add_argument("--ranks", type=int, default=16,
                        help="MPI ranks. 16 physical cores on this machine.")
    parser.add_argument("--nfix-a", type=float, default=0.234,
                        help="Cleveland fixation slope. LPJ-GUESS brackets this "
                             "0.102 to 0.367 and it is worth 18%% on NPP; sweep it "
                             "rather than quoting the central value alone.")
    parser.add_argument("--nfix-b", type=float, default=-0.172)
    parser.add_argument("--driver", type=Path, default=GENERATED / "vesper_driver.bin")
    parser.add_argument("--soilmap", type=Path,
                        default=None)
    parser.add_argument("--pfts", type=Path, default=GENERATED / "vesper_pfts.ins")
    parser.add_argument("--label", default=None,
                        help="human tag for the run directory name")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    if args.soilmap is None:
        import sys as _sys
        _sys.path.insert(0, str(PROJECT_ROOT / 'lib'))
        import builds as _b
        args.soilmap = _b.soilmap()

    for path in (args.driver, args.soilmap, args.pfts, GUESS_BINARY):
        if not Path(path).is_file():
            raise SystemExit(f"{path} is missing")

    config = yaml.safe_load(CONFIG.read_text())

    # The run id pins what the numbers depend on: the forcing, the soil and the
    # compiled planetary constants. Two runs sharing a name share those.
    header = GENERATED / "vesper.h"
    digest = hashlib.sha256(
        (short(args.driver) + short(args.soilmap) + short(header)).encode()
    ).hexdigest()[:8]
    label = f"_{args.label}" if args.label else ""
    run_id = (f"lpj_y{args.nyear}_p{args.npatch}_r{args.ranks}"
              f"_nfix{args.nfix_a:g}{label}_g{digest}")

    run_dir = RUNS / run_id
    if run_dir.exists():
        raise SystemExit(f"{run_dir} exists; delete it or pass a different --label")

    paths = {
        "driver": Path(args.driver).resolve(),
        "soilmap": Path(args.soilmap).resolve(),
        "pfts": (run_dir / "vesper_pfts.ins").resolve(),
    }
    settings = {
        "title": run_id, "nyear": args.nyear, "npatch": args.npatch,
        "nfix_a": args.nfix_a, "nfix_b": args.nfix_b,
    }

    if args.dry_run:
        print(build_instruction(paths, settings))
        return

    run_dir.mkdir(parents=True)
    # The PFT file and everything it imports have to sit together, because plib
    # resolves imports relative to the importing file's directory.
    shutil.copyfile(args.pfts, run_dir / "vesper_pfts.ins")
    for extra in (GUESS_SOURCE / "data" / "ins").glob("*.ins"):
        if not (run_dir / extra.name).exists():
            shutil.copyfile(extra, run_dir / extra.name)

    instruction = run_dir / "run.ins"
    instruction.write_text(build_instruction(paths, settings))
    for rank in range(1, args.ranks + 1):
        (run_dir / f"run{rank}").mkdir(exist_ok=True)

    command = ["mpirun", "-np", str(args.ranks), "--bind-to", "core",
               str(GUESS_BINARY), "-parallel", "-input", "vesper",
               str(instruction.resolve())]
    print(" ".join(command))
    started = time.time()
    result = subprocess.run(command, cwd=run_dir, capture_output=True, text=True)
    elapsed = time.time() - started
    (run_dir / "mpirun.log").write_text(result.stdout + result.stderr)
    if result.returncode != 0:
        raise SystemExit(
            f"LPJ-GUESS exited {result.returncode} after {elapsed:.0f} s. "
            f"See {run_dir / 'mpirun.log'} and {run_dir}/run*/guess.log")

    counts = merge_outputs(run_dir, args.ranks)
    cells = 0
    if (run_dir / "anpp.out").is_file():
        rows = (run_dir / "anpp.out").read_text().splitlines()[1:]
        cells = len({(r.split()[0], r.split()[1]) for r in rows if r.split()})

    manifest = {
        "run_id": run_id,
        "generated": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "wall_seconds": round(elapsed, 1),
        "ranks": args.ranks,
        "settings": settings,
        "cells_simulated": cells,
        "output_rows": counts,
        "inputs": {
            "driver": {"path": str(paths["driver"]), "sha256": sha256(args.driver)},
            "soilmap": {"path": str(paths["soilmap"]), "sha256": sha256(args.soilmap)},
            "pfts": {"path": str(args.pfts), "sha256": sha256(args.pfts)},
            "vesper_h": {"path": str(header), "sha256": sha256(header)},
            "binary": {"path": str(GUESS_BINARY), "sha256": sha256(GUESS_BINARY)},
        },
        "config_sha256": hashlib.sha256(CONFIG.read_bytes()).hexdigest(),
        "source_build": config.get("source_build"),
        "stellar_spectrum": config.get("radiation", {}).get("stellar_spectrum"),
        "orbital_year_earth_days": orbit.orbital_year_days(config),
        "simulation_years_to_earth_years": (
            1.0 / orbit.earth_years_per_orbit(config)),
        "unit_note": (
            "LPJ-GUESS reports per simulation year, which is this world's year. "
            "Multiply by simulation_years_to_earth_years before comparing with "
            "anything quoted per Earth year, including "
            "notes/productivity-prediction.md."),
        "software": {
            "platform": platform.platform(),
            "lpj_guess": "4.1.1 + biosphere/patches/lpj-guess-4.1.1-vesper.patch",
        },
        "git_commit": subprocess.run(
            ["git", "rev-parse", "HEAD"], capture_output=True, text=True,
            cwd=PROJECT_ROOT).stdout.strip() or None,
    }
    (run_dir / "run_manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    analysis_dir = ANALYSIS / run_id
    analysis_dir.mkdir(parents=True, exist_ok=True)
    (analysis_dir / "run_manifest.json").write_text(
        json.dumps(manifest, indent=2) + "\n")

    print(f"\n{run_id}")
    print(f"  {cells} cells, {elapsed:.0f} s wall on {args.ranks} ranks")
    print(f"  output   {run_dir}")
    print(f"  manifest {analysis_dir / 'run_manifest.json'}")


if __name__ == "__main__":
    main()
